config/routes.rb
# == Route Map
#
#                 Prefix Verb   URI Pattern                                         Controller#Action
#                   root GET    /                                                   pages#home
#                   shop GET    /shop/:gender(.:format)                             pages#shop
#      products_category GET    /shop/:gender/:category(.:format)                   pages#category
#                        GET    /products/gender/:gender(.:format)                  products#search
#                  users GET    /users(.:format)                                    users#index
#                        POST   /users(.:format)                                    users#create
#               new_user GET    /users/new(.:format)                                users#new
#              edit_user GET    /users/:id/edit(.:format)                           users#edit
#                   user GET    /users/:id(.:format)                                users#show
#                        PATCH  /users/:id(.:format)                                users#update
#                        PUT    /users/:id(.:format)                                users#update
#                        DELETE /users/:id(.:format)                                users#destroy
#             categories GET    /categories(.:format)                               categories#index
#                        POST   /categories(.:format)                               categories#create
#           new_category GET    /categories/new(.:format)                           categories#new
#          edit_category GET    /categories/:id/edit(.:format)                      categories#edit
#               category GET    /categories/:id(.:format)                           categories#show
#                        PATCH  /categories/:id(.:format)                           categories#update
#                        PUT    /categories/:id(.:format)                           categories#update
#                        DELETE /categories/:id(.:format)                           categories#destroy
#     product_favourites GET    /products/:product_id/favourites(.:format)          favourites#index
#                        POST   /products/:product_id/favourites(.:format)          favourites#create
#  new_product_favourite GET    /products/:product_id/favourites/new(.:format)      favourites#new
# edit_product_favourite GET    /products/:product_id/favourites/:id/edit(.:format) favourites#edit
#      product_favourite GET    /products/:product_id/favourites/:id(.:format)      favourites#show
#                        PATCH  /products/:product_id/favourites/:id(.:format)      favourites#update
#                        PUT    /products/:product_id/favourites/:id(.:format)      favourites#update
#                        DELETE /products/:product_id/favourites/:id(.:format)      favourites#destroy
#        product_reviews GET    /products/:product_id/reviews(.:format)             reviews#index
#                        POST   /products/:product_id/reviews(.:format)             reviews#create
#     new_product_review GET    /products/:product_id/reviews/new(.:format)         reviews#new
#    edit_product_review GET    /products/:product_id/reviews/:id/edit(.:format)    reviews#edit
#         product_review GET    /products/:product_id/reviews/:id(.:format)         reviews#show
#                        PATCH  /products/:product_id/reviews/:id(.:format)         reviews#update
#                        PUT    /products/:product_id/reviews/:id(.:format)         reviews#update
#                        DELETE /products/:product_id/reviews/:id(.:format)         reviews#destroy
#         product_images GET    /products/:product_id/images(.:format)              images#index
#                        POST   /products/:product_id/images(.:format)              images#create
#      new_product_image GET    /products/:product_id/images/new(.:format)          images#new
#     edit_product_image GET    /products/:product_id/images/:id/edit(.:format)     images#edit
#          product_image GET    /products/:product_id/images/:id(.:format)          images#show
#                        PATCH  /products/:product_id/images/:id(.:format)          images#update
#                        PUT    /products/:product_id/images/:id(.:format)          images#update
#                        DELETE /products/:product_id/images/:id(.:format)          images#destroy
#     product_line_items GET    /products/:product_id/line_items(.:format)          line_items#index
#                        POST   /products/:product_id/line_items(.:format)          line_items#create
#  new_product_line_item GET    /products/:product_id/line_items/new(.:format)      line_items#new
# edit_product_line_item GET    /products/:product_id/line_items/:id/edit(.:format) line_items#edit
#      product_line_item GET    /products/:product_id/line_items/:id(.:format)      line_items#show
#                        PATCH  /products/:product_id/line_items/:id(.:format)      line_items#update
#                        PUT    /products/:product_id/line_items/:id(.:format)      line_items#update
#                        DELETE /products/:product_id/line_items/:id(.:format)      line_items#destroy
#               products GET    /products(.:format)                                 products#index
#                        POST   /products(.:format)                                 products#create
#            new_product GET    /products/new(.:format)                             products#new
#           edit_product GET    /products/:id/edit(.:format)                        products#edit
#                product GET    /products/:id(.:format)                             products#show
#                        PATCH  /products/:id(.:format)                             products#update
#                        PUT    /products/:id(.:format)                             products#update
#                        DELETE /products/:id(.:format)                             products#destroy
#                 orders GET    /orders(.:format)                                   orders#index
#                        POST   /orders(.:format)                                   orders#create
#              new_order GET    /orders/new(.:format)                               orders#new
#             edit_order GET    /orders/:id/edit(.:format)                          orders#edit
#                  order GET    /orders/:id(.:format)                               orders#show
#                        PATCH  /orders/:id(.:format)                               orders#update
#                        PUT    /orders/:id(.:format)                               orders#update
#                        DELETE /orders/:id(.:format)                               orders#destroy
#                  login GET    /login(.:format)                                    session#new
#                        POST   /login(.:format)                                    session#create
#                        DELETE /login(.:format)                                    session#destroy
#

Rails.application.routes.draw do


  get 'chatbot/show' => 'chatbot#show'

  root :to => 'pages#home'
  get '/shop/:gender' => 'pages#shop', :as => 'shop'
  get '/shop/:gender/:category' => 'pages#category', :as => 'products_category'

  get '/products/gender/:gender' => 'products#search'

  get'/wishlist' => 'users#wishlist', :as => 'wishlist'

  resources :users
  resources :categories
  resources :products do
    resources :favourites
    resources :reviews
    resources :images
    resources :line_items
  end

  delete '/line_items/:id' => 'line_items#destroy', :as => 'lineitem_destroy'

  resources :orders do
    resources :charges
  end

  get '/thanks' => 'charges#thanks'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  status     :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ActiveRecord::Base
  belongs_to :user
  # if delete an order it will delete the line items asscoiated with it from the db
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

#create array line items
# sums the total_cost as calculated in line_items.rb
  def total_cost
    line_items.to_a.sum {|item| item.total_cost}
  end



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @customer_order = Order.find params[:id]
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
  end

  def edit
    @order = Order.find params[:id]
  end

  def update
    order = Order.find params[:id]
    order.update order_params
    redirect_to #the page that you were on
  end

  def destroy
    @order = Order.find params[:id]
    @order.destroy if @order.id == session[:order_id]
    session[:order_id] = nil

    respond_to do |format|
      format.html {redirect_to root_path, notice: 'Your cart is currently empty'}
    end

    # redirect_to shop_path
    #the page that you were on
  end

  def remove_item product_id, order_item
    order_item.delete(product_id)
  end


  private

  def order_params
    params.require(:order).permit(:user_id, :status, :id)
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_show_order.html.erb
<table class="table table-striped table-hover">

  <tr>
    <td> </td>
    <td>Product</td>
    <td>Size</td>
    <td>Unit Price</td>
    <td>Quantity</td>
    <td>Total Price</td>
    <td> </td>
  </tr>

  <% @order.line_items.each do |item| %>
    <tr>
      <td><%= item.product.images[0] %></td>
      <td><%= item.product.name %></td>
      <td><%= item.product.size %></td>
      <td><%= number_to_currency(item.product.cost) %></td>
      <td><%= item.quantity %></td>
      <td><%= number_to_currency(item.quantity * item.product.cost) %></td>
    </tr>
  <% end %>

      <tr>
        <td colspan="5" ></td>
        <td colspan="2" class="totalCost"><%= number_to_currency(@order.total_cost) %></td>
      </tr>

</table>

app/views/orders/index.html.erb
<div class="container">
  <%=  render :partial => 'layouts/navbarInner' %>
  <h1>Listing Orders</h1>

  <table class=table>
    <thead>
      <tr>
        <td>ORDER ID</td>
        <td>STATUS</td>
        <td>USER ID</td>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%=link_to "#{order.id}", order_path(order.id) %></td>
          <td><%= order.status %> </td>
          <td><%= order.user_id %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/orders/show.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

<div class="container">
  <h2>Your Cart</h2>
  <table class="table">

    <tr>
      <td> </td>
      <td>Product</td>
      <td>Size</td>
      <td>Unit Price</td>
      <td>Quantity</td>
      <td>Total Price</td>
      <td> </td>
    </tr>


    <% @customer_order.line_items.each do |item| %>
      <tr>
        <td><%= cl_image_tag(item.product.images[0], :style => "height:150px") %></td>
        <td><%= item.product.name %></td>
        <td><%= item.product.size %></td>
        <td><%= number_to_currency(item.product.cost) %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.quantity * item.product.cost) %></td>
        <td><%= link_to 'x', lineitem_destroy_path(item.id), :method => 'delete' %></td>
      </tr>
    <% end %>

    <tr>
      <td colspan="5" ></td>
      <td colspan="2" class="totalCost"><%= number_to_currency(@order.total_cost) %></td>
    </tr>

  </table>

  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= link_to "Checkout", new_order_charge_path(:order_id => @order.id), :class=>"btnborder btn btn-primary"%>
      <%= link_to 'Empty cart', @order, method: :delete, data: {confirm: 'Are you sure you want to empty your cart?'}, :class=>"btnborder btn btn-primary " %>
    </div>
    <div class="col-md-4"></div>
  </div>

</div>