config/routes.rb
# == Route Map
#
#                 Prefix Verb   URI Pattern                                         Controller#Action
#                   root GET    /                                                   pages#home
#                   shop GET    /shop/:gender(.:format)                             pages#shop
#      products_category GET    /shop/:gender/:category(.:format)                   pages#category
#                        GET    /products/gender/:gender(.:format)                  products#search
#                  users GET    /users(.:format)                                    users#index
#                        POST   /users(.:format)                                    users#create
#               new_user GET    /users/new(.:format)                                users#new
#              edit_user GET    /users/:id/edit(.:format)                           users#edit
#                   user GET    /users/:id(.:format)                                users#show
#                        PATCH  /users/:id(.:format)                                users#update
#                        PUT    /users/:id(.:format)                                users#update
#                        DELETE /users/:id(.:format)                                users#destroy
#             categories GET    /categories(.:format)                               categories#index
#                        POST   /categories(.:format)                               categories#create
#           new_category GET    /categories/new(.:format)                           categories#new
#          edit_category GET    /categories/:id/edit(.:format)                      categories#edit
#               category GET    /categories/:id(.:format)                           categories#show
#                        PATCH  /categories/:id(.:format)                           categories#update
#                        PUT    /categories/:id(.:format)                           categories#update
#                        DELETE /categories/:id(.:format)                           categories#destroy
#     product_favourites GET    /products/:product_id/favourites(.:format)          favourites#index
#                        POST   /products/:product_id/favourites(.:format)          favourites#create
#  new_product_favourite GET    /products/:product_id/favourites/new(.:format)      favourites#new
# edit_product_favourite GET    /products/:product_id/favourites/:id/edit(.:format) favourites#edit
#      product_favourite GET    /products/:product_id/favourites/:id(.:format)      favourites#show
#                        PATCH  /products/:product_id/favourites/:id(.:format)      favourites#update
#                        PUT    /products/:product_id/favourites/:id(.:format)      favourites#update
#                        DELETE /products/:product_id/favourites/:id(.:format)      favourites#destroy
#        product_reviews GET    /products/:product_id/reviews(.:format)             reviews#index
#                        POST   /products/:product_id/reviews(.:format)             reviews#create
#     new_product_review GET    /products/:product_id/reviews/new(.:format)         reviews#new
#    edit_product_review GET    /products/:product_id/reviews/:id/edit(.:format)    reviews#edit
#         product_review GET    /products/:product_id/reviews/:id(.:format)         reviews#show
#                        PATCH  /products/:product_id/reviews/:id(.:format)         reviews#update
#                        PUT    /products/:product_id/reviews/:id(.:format)         reviews#update
#                        DELETE /products/:product_id/reviews/:id(.:format)         reviews#destroy
#         product_images GET    /products/:product_id/images(.:format)              images#index
#                        POST   /products/:product_id/images(.:format)              images#create
#      new_product_image GET    /products/:product_id/images/new(.:format)          images#new
#     edit_product_image GET    /products/:product_id/images/:id/edit(.:format)     images#edit
#          product_image GET    /products/:product_id/images/:id(.:format)          images#show
#                        PATCH  /products/:product_id/images/:id(.:format)          images#update
#                        PUT    /products/:product_id/images/:id(.:format)          images#update
#                        DELETE /products/:product_id/images/:id(.:format)          images#destroy
#     product_line_items GET    /products/:product_id/line_items(.:format)          line_items#index
#                        POST   /products/:product_id/line_items(.:format)          line_items#create
#  new_product_line_item GET    /products/:product_id/line_items/new(.:format)      line_items#new
# edit_product_line_item GET    /products/:product_id/line_items/:id/edit(.:format) line_items#edit
#      product_line_item GET    /products/:product_id/line_items/:id(.:format)      line_items#show
#                        PATCH  /products/:product_id/line_items/:id(.:format)      line_items#update
#                        PUT    /products/:product_id/line_items/:id(.:format)      line_items#update
#                        DELETE /products/:product_id/line_items/:id(.:format)      line_items#destroy
#               products GET    /products(.:format)                                 products#index
#                        POST   /products(.:format)                                 products#create
#            new_product GET    /products/new(.:format)                             products#new
#           edit_product GET    /products/:id/edit(.:format)                        products#edit
#                product GET    /products/:id(.:format)                             products#show
#                        PATCH  /products/:id(.:format)                             products#update
#                        PUT    /products/:id(.:format)                             products#update
#                        DELETE /products/:id(.:format)                             products#destroy
#                 orders GET    /orders(.:format)                                   orders#index
#                        POST   /orders(.:format)                                   orders#create
#              new_order GET    /orders/new(.:format)                               orders#new
#             edit_order GET    /orders/:id/edit(.:format)                          orders#edit
#                  order GET    /orders/:id(.:format)                               orders#show
#                        PATCH  /orders/:id(.:format)                               orders#update
#                        PUT    /orders/:id(.:format)                               orders#update
#                        DELETE /orders/:id(.:format)                               orders#destroy
#                  login GET    /login(.:format)                                    session#new
#                        POST   /login(.:format)                                    session#create
#                        DELETE /login(.:format)                                    session#destroy
#

Rails.application.routes.draw do


  get 'chatbot/show' => 'chatbot#show'

  root :to => 'pages#home'
  get '/shop/:gender' => 'pages#shop', :as => 'shop'
  get '/shop/:gender/:category' => 'pages#category', :as => 'products_category'

  get '/products/gender/:gender' => 'products#search'

  get'/wishlist' => 'users#wishlist', :as => 'wishlist'

  resources :users
  resources :categories
  resources :products do
    resources :favourites
    resources :reviews
    resources :images
    resources :line_items
  end

  delete '/line_items/:id' => 'line_items#destroy', :as => 'lineitem_destroy'

  resources :orders do
    resources :charges
  end

  get '/thanks' => 'charges#thanks'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  cost       :integer
#  size       :string
#  color      :string
#  gender     :string
#  brand      :text
#  info       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :text
#  images     :text             default("{}"), is an Array
#

class Product < ActiveRecord::Base

  has_many :favourites
  has_many :reviews
  has_many :line_items, dependent: :destroy
  has_and_belongs_to_many :categories
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all


  end

  def search
    @products = Product.where :gender => params[:gender]
  end

  def show
    session[:prev_url]= request.referer
  end

  def new
    @products = Product.all
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if params[:product][:images].present?
      params[:product][:images].each do |image|
        req = Cloudinary::Uploader.upload(image)
        @product.images << req["public_id"]
      end
    end
    if @product.save
      flash[:create] = "Product created successfully"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    session[:prev_url]= request.referer
  end

  def update
    if params[:product][:images].present?
      params[:product][:images].each do |image|
        req = Cloudinary::Uploader.upload(image)
        @product.images << req["public_id"]
      end
    end

    @product.update_attributes(product_params)

    if @product.save
      flash[:create] = "Product updated successfully"
      redirect_to session.delete(:prev_url)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back
    else
      redirect_to session.delete(:prev_url)
    end
    # respond_to do |format|
    #   format.html { redirect_to session.delete(:prev_url) , notice: 'Product is successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find params[:id]
  end

  def product_params
    params.require(:product).permit(:name, :cost, :size, :color, :gender, :brand, :info, :category_ids)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form2.html.erb
<div class="row">


<div class="col-md-11">
<%= form_for(@product, :html=>{:multipart=>true}) do |f| %>

<div class="form-group">
  *<%= f.label :name %>
  <%= f.text_field :name, :autofocus=>true, :required => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
  *<%= f.label :cost %>
  <%= f.number_field :cost, :required => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
  *<%= f.label :size %>
  <%= f.text_field :size, :required => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
  *<%= f.label :color %>
  <%= f.text_field :color, :required => true, :class=>"form-control textfield-border" %>
</div>

<div class="form-group">
  *<%= f.label :brand %>
  <%= f.text_field :brand, :required => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
  *<%= f.label :info %>
  <%= f.text_field :info, :required => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
  *<%= f.label :images %>
  <%= f.file_field :images, :multiple => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
    *<%= f.label :gender %>
    <%= f.select :gender, [['women'],['men'],['unisex']], :include_blank => false, :required => true %>
</div>
<div class="form-group">

    *<%= f.label :category %>
    <%= f.collection_select :category_ids, Category.all, :id, :name, :multiple => true, :prompt => 'Select'%>
</div>
<div class="button-center">
  <%= f.submit 'Submit', :class=>"btnblack btnborder btn btn-primary" %>
</div>
<% end %>

</div>
<div class="col-md-1"></div>
</div>

app/views/products/_list.html.erb
<table class="table table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th></th>
      <th></th>
  </tr>
<% @products.each do |p| %>
<tr>
  <td>
    <%= link_to p.name, product_path(p.id) %>
  </td>
  <td>

    <%if p.gender == "women"%>
    F
    <% else %>
    M
    <% end %>
  </td>
  <td>
    <%= link_to "Edit", edit_product_path(p.id)%>
  </td>
  <td>
    <%= link_to "Delete", product_path(p.id),
                                  :method=>"delete", :data=>{:confirm=>"Are you sure?"} %>
  </td>
  </div>
</tr>

<% end %>
</table>

app/views/products/edit.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-5">
    <h1>Edit product</h1>
    <% if @product.errors.any? %>
      <ol>
      <% @product.errors.full_messages.each do |msg| %>
        <li class="bg-danger"><%= msg %></li>
      <% end %>
      </ol>
    <% end %>
    <%= render :partial=>"form2" %>
  </div>
  <div class="col-md-6"></div>
</div>

app/views/products/index.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

<div class="row">

  <div class="col-md-1"></div>

    <div class="col-md-5">
      <h1>All Products</h1>
      <%=  render :partial => 'products/list' %>
    </div>
  <div class="col-md-5">

  </div>
  <div class="col-md-1"></div>
</div>

app/views/products/new.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

<div class="row">

  <div class="col-md-1"></div>

    <div class="col-md-5">
      <h1>New Product</h1>
        <% if @product.errors.any? %>
          <ol>
          <% @product.errors.full_messages.each do |msg| %>
            <li class="bg-danger"><%= msg %></li>
          <% end %>
          </ol>
        <% end %>

      <%= render :partial => "form2" %>

    </div>
  <div class="col-md-5">
    
  </div>
  <div class="col-md-1"></div>
</div>

app/views/products/show.html.erb
<%=  render :partial => 'layouts/navbarInner' %>


<div class="container">
  <div class="row">
    <div class='col-md-6'>
      <% if @current_user.admin %>
        <div class = "adminProductsShow">
          <%= link_to "Edit", edit_product_path(@product.id), :class=>"adminbtn btnblack btnborder btn btn-primary " %>
          <%= link_to "Delete", product_path(@product.id), :method=>"delete",:class=>"adminbtn btnblack btnborder btn btn-primary " , :data=>{:confirm=>"Are you sure?"} %>
        </div>
      <% end %>
      <h3><%= @product.name %></h3>
      <br>
      <p>Price : <span id="price"><%= number_to_currency(@product.cost)%></span></p>
      <p>Designed by : <span class="green"><%= @product.brand %></span></p>
      <p>Color : <span class="green"><%= @product.color %></span></p>
      <br>
      <p><%= @product.info %></p>
      <% if @current_user.present? %>
        <div>
          <% if flash[:error].present? %>
            <p class="bg-danger"><%= flash[:error] %></p>
          <% end %>
          <% if flash[:msg].present? %>
            <p class="bg-danger"><%= flash[:msg] %></p>
          <% end %>
          <%= link_to "Add to Cart", product_line_items_path(product_id: @product.id), :method=>"post", :class=>"btnblack btnborder btn btn-primary" %>
        </div>
        <div class="button-center">
          <% if @current_user.already_likes?(@product) %>
            <%= link_to "Remove from Wishlist", product_favourite_path(:product_id=>@product.id, :user_id=>@current_user.id),
                                  :method=>"delete", :class=>"btnblack btnborder btn btn-primary "%>
          <% else %>

            <%= link_to "Add to Wishlist", product_favourites_path(:product_id=>@product.id, :user_id=>@current_user.id),
                                  :method=>"post", :class=>"btnblack btnborder btn btn-primary " %>

          <% end %>
        </div>
        <% end %>
    </div>

    <div class='col-md-6'>
        <% @product.images.each do |i| %>
          <%= cl_image_tag i, :class=>"productListThumb"  %>
        <% end %>
    </div>
  </div>

  <div>
    <h4><strong>Reviews</strong></h4>
    <% if @current_user.present? %>
      <%= form_for([@product, @product.reviews.build]) do |f| %>
        <%= hidden_field_tag :user_id, @current_user.id %>
        <div class="form-groupshow">
          <% if flash[:review_error].present? %>
            <p class="bg-danger"><%= flash[:review_error] %></p>
          <% end %>
          <%= f.text_area :desc, :class=>"form-control textfield-border"  %>
          <%= f.submit 'Add Review', :class=>"btnblack btnshowborder btn btn-primaryshow" %>
        </div>
      <% end %>
    <% end %>
    <% @product.reviews.each do |review| %>
      <p><i class="fa fa-comment-o" aria-hidden="true"></i>
        <%= review.desc %>
      </p>
    <% end %>
  </div>

</div>