config/routes.rb
# == Route Map
#
#                 Prefix Verb   URI Pattern                                         Controller#Action
#                   root GET    /                                                   pages#home
#                   shop GET    /shop/:gender(.:format)                             pages#shop
#      products_category GET    /shop/:gender/:category(.:format)                   pages#category
#                        GET    /products/gender/:gender(.:format)                  products#search
#                  users GET    /users(.:format)                                    users#index
#                        POST   /users(.:format)                                    users#create
#               new_user GET    /users/new(.:format)                                users#new
#              edit_user GET    /users/:id/edit(.:format)                           users#edit
#                   user GET    /users/:id(.:format)                                users#show
#                        PATCH  /users/:id(.:format)                                users#update
#                        PUT    /users/:id(.:format)                                users#update
#                        DELETE /users/:id(.:format)                                users#destroy
#             categories GET    /categories(.:format)                               categories#index
#                        POST   /categories(.:format)                               categories#create
#           new_category GET    /categories/new(.:format)                           categories#new
#          edit_category GET    /categories/:id/edit(.:format)                      categories#edit
#               category GET    /categories/:id(.:format)                           categories#show
#                        PATCH  /categories/:id(.:format)                           categories#update
#                        PUT    /categories/:id(.:format)                           categories#update
#                        DELETE /categories/:id(.:format)                           categories#destroy
#     product_favourites GET    /products/:product_id/favourites(.:format)          favourites#index
#                        POST   /products/:product_id/favourites(.:format)          favourites#create
#  new_product_favourite GET    /products/:product_id/favourites/new(.:format)      favourites#new
# edit_product_favourite GET    /products/:product_id/favourites/:id/edit(.:format) favourites#edit
#      product_favourite GET    /products/:product_id/favourites/:id(.:format)      favourites#show
#                        PATCH  /products/:product_id/favourites/:id(.:format)      favourites#update
#                        PUT    /products/:product_id/favourites/:id(.:format)      favourites#update
#                        DELETE /products/:product_id/favourites/:id(.:format)      favourites#destroy
#        product_reviews GET    /products/:product_id/reviews(.:format)             reviews#index
#                        POST   /products/:product_id/reviews(.:format)             reviews#create
#     new_product_review GET    /products/:product_id/reviews/new(.:format)         reviews#new
#    edit_product_review GET    /products/:product_id/reviews/:id/edit(.:format)    reviews#edit
#         product_review GET    /products/:product_id/reviews/:id(.:format)         reviews#show
#                        PATCH  /products/:product_id/reviews/:id(.:format)         reviews#update
#                        PUT    /products/:product_id/reviews/:id(.:format)         reviews#update
#                        DELETE /products/:product_id/reviews/:id(.:format)         reviews#destroy
#         product_images GET    /products/:product_id/images(.:format)              images#index
#                        POST   /products/:product_id/images(.:format)              images#create
#      new_product_image GET    /products/:product_id/images/new(.:format)          images#new
#     edit_product_image GET    /products/:product_id/images/:id/edit(.:format)     images#edit
#          product_image GET    /products/:product_id/images/:id(.:format)          images#show
#                        PATCH  /products/:product_id/images/:id(.:format)          images#update
#                        PUT    /products/:product_id/images/:id(.:format)          images#update
#                        DELETE /products/:product_id/images/:id(.:format)          images#destroy
#     product_line_items GET    /products/:product_id/line_items(.:format)          line_items#index
#                        POST   /products/:product_id/line_items(.:format)          line_items#create
#  new_product_line_item GET    /products/:product_id/line_items/new(.:format)      line_items#new
# edit_product_line_item GET    /products/:product_id/line_items/:id/edit(.:format) line_items#edit
#      product_line_item GET    /products/:product_id/line_items/:id(.:format)      line_items#show
#                        PATCH  /products/:product_id/line_items/:id(.:format)      line_items#update
#                        PUT    /products/:product_id/line_items/:id(.:format)      line_items#update
#                        DELETE /products/:product_id/line_items/:id(.:format)      line_items#destroy
#               products GET    /products(.:format)                                 products#index
#                        POST   /products(.:format)                                 products#create
#            new_product GET    /products/new(.:format)                             products#new
#           edit_product GET    /products/:id/edit(.:format)                        products#edit
#                product GET    /products/:id(.:format)                             products#show
#                        PATCH  /products/:id(.:format)                             products#update
#                        PUT    /products/:id(.:format)                             products#update
#                        DELETE /products/:id(.:format)                             products#destroy
#                 orders GET    /orders(.:format)                                   orders#index
#                        POST   /orders(.:format)                                   orders#create
#              new_order GET    /orders/new(.:format)                               orders#new
#             edit_order GET    /orders/:id/edit(.:format)                          orders#edit
#                  order GET    /orders/:id(.:format)                               orders#show
#                        PATCH  /orders/:id(.:format)                               orders#update
#                        PUT    /orders/:id(.:format)                               orders#update
#                        DELETE /orders/:id(.:format)                               orders#destroy
#                  login GET    /login(.:format)                                    session#new
#                        POST   /login(.:format)                                    session#create
#                        DELETE /login(.:format)                                    session#destroy
#

Rails.application.routes.draw do


  get 'chatbot/show' => 'chatbot#show'

  root :to => 'pages#home'
  get '/shop/:gender' => 'pages#shop', :as => 'shop'
  get '/shop/:gender/:category' => 'pages#category', :as => 'products_category'

  get '/products/gender/:gender' => 'products#search'

  get'/wishlist' => 'users#wishlist', :as => 'wishlist'

  resources :users
  resources :categories
  resources :products do
    resources :favourites
    resources :reviews
    resources :images
    resources :line_items
  end

  delete '/line_items/:id' => 'line_items#destroy', :as => 'lineitem_destroy'

  resources :orders do
    resources :charges
  end

  get '/thanks' => 'charges#thanks'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/views/layouts/_navbarHomepage.html.erb
<nav class="navbar-inner navbar navbar-fixed-top navbar--color--secondary navbar--size--md" data-startcolor="navbar--color--ghost" data-startsize="navbar--size--xl" data-intocolor="navbar--color--secondary" data-intosize="navbar--size--md">
<div class="container">

<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mobileNav" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

  <%= link_to "GetFashion", root_path, :class => " brandphoto navbar-brand" %>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="mobileNav">
  <ul class="nav navbar-nav">
    <!-- <li><%= link_to "categories", categories_path %></li> -->
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <% if !@current_user.present? %>
    <li>
      <%= link_to "Men", shop_path(:gender => 'men'), :class => "blackfont"%>
    </li>
    <li>
      <%= link_to "Women", shop_path(:gender => 'women'), :class => "blackfont"%>
    </li>

    <li><%= link_to "Join", new_user_path, :class => "blackfont" %></li>
    <!-- <li><%= link_to "Sign in", login_path, :class => "blackfont" %></li> -->
    <li class="dropdown">
      <a href="#" class="dropdown-toggle blackfont" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
      <ul id="login-dp" class="dropdown-menu">
      <li>
        <div class="row">
          <div class="col-md-12">
            <%= form_tag login_path, :class => 'form', :id => 'login-nav' do %>
              <div class="form-group">
                <label class="sr-only" for="exampleInputEmail2">Email address</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail2" placeholder="Email address" required>
              </div>
              <div class="form-group">
                 <label class="sr-only" for="exampleInputPassword2">Password</label>
                 <input type="password" name="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
              </div>
              <div class="form-group">
                 <button id="btn-login" type="submit" class="btn btn-primary btnborder btn-block">Sign in</button>
              </div>
            <% end %>
          </div>
         </div>
        </li>
      </ul>
    </li>

    <% end %>

    <% if @current_user.present? %>
      <li>
        <%= link_to "Men", shop_path(:gender => 'men'), :class => "blackfont"%>
      </li>
      <li>
        <%= link_to "Women", shop_path(:gender => 'women'), :class => "blackfont"%>
      </li>

      <li class=" dropdown">
        <a href="#" class="blackfont dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= "#{@current_user.name}" %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu" >
          <li ><%= link_to "Wishlist", wishlist_path, :id=>"drop" %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Edit profile", edit_user_path(@current_user.id), :id=>"drop" %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Logout", login_path, :method => 'delete', :id=>"drop" %></li>
        </ul>
      </li>
    <% end %>

    <% if @current_user.present? %>
    <% if @current_user.admin %>
        <li class=" dropdown">
          <a href="#" class=" blackfont dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All Products", products_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "New Product", new_product_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "All Categories", categories_path %></li>
          <li role="separator" class="divider"></li>

          <li><%= link_to "New Category", new_category_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Users", users_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Orders", orders_path %></li>
        </ul>
      </li>
      <% end %>

      <li >
        <%= link_to order_path(:id => @order.id) do%><i id="cart-icon" class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i><% end %>
      </li>

    <% end %>



  </ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbarInner.html.erb
<nav class="navbar navbar-fixed-top navbar--color--secondary navbar--size--md navbar-inner" data-startcolor="navbar--color--ghost" data-startsize="navbar--size--xl" data-intocolor="navbar--color--secondary" data-intosize="navbar--size--md">
<div class="container">

<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mobileNav" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

  <%= link_to "GetFashion", root_path, :class => "brandphoto navbar-brand" %>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="mobileNav">
  <ul class="nav navbar-nav">
    <!-- <li><%= link_to "categories", categories_path %></li> -->
  </ul>
  <ul class="nav navbar-nav navbar-right">

    <% if !@current_user.present? %>
    <li>
      <%= link_to "Men", shop_path(:gender => 'men'), :class => "blackfont"%>
    </li>
    <li>
      <%= link_to "Women", shop_path(:gender => 'women'), :class => "blackfont"%>
    </li>
    <li><%= link_to "Join", new_user_path, :class => "blackfont" %></li>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle blackfont" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
      <ul id="login-window" class="dropdown-menu">
      <li>
        <div class="row">
          <div class="col-md-12">
            <%= form_tag login_path, :class => 'form', :id => 'login-nav' do %>
              <div class="form-group">
                <label class="sr-only" for="exampleInputEmail2">Email address</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail2" placeholder="Email address" required>
              </div>
              <div class="form-group">
                 <label class="sr-only" for="exampleInputPassword2">Password</label>
                 <input type="password" name="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
              </div>
              <div class="form-group">
                 <button type="submit" class="btn btn-primary btnborder btn-block">Sign in</button>
              </div>
            <% end %>
          </div>
         </div>
        </li>
      </ul>
    </li>

    <% end %>



    <% if @current_user.present? %>
      <li>
        <%= link_to "Men", shop_path(:gender => 'men'), :class => "blackfont"%>
      </li>
      <li>
        <%= link_to "Women", shop_path(:gender => 'women'), :class => "blackfont"%>
      </li>
      <li class=" dropdown">
        <a href="#" class="blackfont dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= "#{@current_user.name}" %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Wishlist", wishlist_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Edit profile", edit_user_path(@current_user.id) %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Logout", login_path, :method => 'delete' %></li>
        </ul>
      </li>
    <% end %>

    <% if @current_user.present? %>
    <% if @current_user.admin %>
      <li class=" dropdown">
        <a href="#" class=" blackfont dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All Products", products_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "New Product", new_product_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "All Categories", categories_path %></li>
          <li role="separator" class="divider"></li>

          <li><%= link_to "New Category", new_category_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Users", users_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Orders", orders_path %></li>
        </ul>
      </li>
      <% end %>
      <li>
        <%= link_to order_path(:id => @order.id) do%><i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i><% end %>
      </li>

    <% end %>

  </ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Get Fashions</title>

  <!-- <%= cloudinary_js_config %> -->
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>

  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

   <script type="text/javascript">
    Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
   </script>

</head>
<body>



<body class="<%= params[:controller] %> <%=params[:action]%>">

<div class="wrapper">
  <%= yield %>
</div>

<% unless current_page?(root_path) %>
<h1 class="chat-header">Need help???<span class="hideChat">hide</span></h1>
<div class="chat-window">
  <div class="chat-history"></div>
</div>
<div class="chat-input">
  <%= render :partial => "chatbot/chat" %>
</div>
<div class="showChat">
  <i class="fa fa-comment-o" aria-hidden="true"></i> Need help???
</div>
<% end %>

<div class='spacer'></div>

</body>
</html>